<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../.resources/report.css" type="text/css"/><link rel="shortcut icon" href="../.resources/report.gif" type="image/gif"/><title>Clase_4.java</title><link rel="stylesheet" href="../.resources/prettify.css" type="text/css"/><script type="text/javascript" src="../.resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../.sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">JaCoCoverage analysis of project &quot;Clase_4&quot; (powered by JaCoCo from EclEmma)</a> &gt; <a href="index.source.html" class="el_package">clase_4</a> &gt; <span class="el_source">Clase_4.java</span></div><h1>Clase_4.java</h1><pre class="source lang-java linenums">package clase_4;

<span class="nc" id="L3">public class Clase_4 {</span>

    public static void main(String[] args) {

        // Runtime exception. Al momento de ejecucion
        /*
        int a = 5;
        int b = 0;
        
        int division = a / b;
        
        System.out.println( &quot;Resultado = &quot; + division );
        */
        
        // Indice fuera Y div entre 0

<span class="fc" id="L19">        String[] nombres = { &quot;AAAAA&quot;, &quot;BBBBB&quot;, &quot;CCCCC&quot; };</span>
        
        // Al ocurrir una excepcion, se va SOLO a un catch
        try{
<span class="nc" id="L23">            int div = 1/0;</span>
<span class="nc bnc" id="L24" title="All 2 branches missed.">            for( int i = 0; i &lt;= nombres.length; i++ ){</span>
<span class="nc" id="L25">                System.out.println( &quot;Nombre[&quot; + i + &quot;]: &quot; + nombres[i] );</span>
            }
        } 
        // Multicatch (usado para excepciones similares)
<span class="fc" id="L29">        catch( ArithmeticException | ArrayIndexOutOfBoundsException e ){</span>
<span class="pc bpc" id="L30" title="1 of 2 branches missed.">            if( e instanceof ArithmeticException ){</span>
<span class="fc" id="L31">                System.out.println( &quot;Excepcion ArithmeticException&quot; );</span>
            } else{
<span class="nc" id="L33">                System.out.println( &quot;Excepcion ArrayIndexOutOfBoundsException&quot; );</span>
            }
        }
        
        /*
        catch( ArithmeticException e ){
            System.out.println( &quot;Fallo al intentar dividir&quot; );
            e.printStackTrace();
        } catch( ArrayIndexOutOfBoundsException e ){
            System.out.println( &quot;Fallo el ciclo: &quot; + e.getMessage() );
            e.printStackTrace();
        }
        */
        
<span class="nc" id="L47">        catch( Exception e ){</span>
<span class="nc" id="L48">            e.printStackTrace();</span>
        }finally{
<span class="pc" id="L50">            System.out.println( &quot;Bloque Finally&quot; );</span>
<span class="pc" id="L51">            System.out.println( &quot;Liberando Recursos&quot; );</span>
<span class="pc" id="L52">        }</span>
        
<span class="fc" id="L54">        System.out.println( &quot;Continua la ejecucion&quot; );</span>

<span class="fc" id="L56">    }</span>
    
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.eclemma.org/jacoco">JaCoCo</a> 0.7.6.201602180812</span></div></body></html>